In [3]:
#Pandas Series 
import numpy as np
import pandas as pd 
labels = ['a', 'b' , 'c']
my_list = [10,20,30]
arr = np.array(my_list)
print (arr)
d = {'a':10, 'b':20, 'c':30}
pd.Series(data = my_list)


[10 20 30]


0    10
1    20
2    30
dtype: int64

In [8]:
#Series with Index
a=pd.Series(data= my_list, index=labels)
#Series with index (given index)
c=pd.Series(data=my_list, index = ['A','B','C'])
print(a)
print(c)

a    10
b    20
c    30
dtype: int64
A    10
B    20
C    30
dtype: int64


In [5]:
#Series with arr
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [6]:
#Series with dict
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [14]:
#Dataframe - 2d labeled 
import numpy as np
import pandas as pd
from numpy.random import randn
pd.DataFrame(randn(5,4), index= ['A','B', 'C', 'D', 'E'],columns=['W', 'X','Y','Z'])

W         X         Y         Z
A -0.754298  1.148475  0.029137  0.064605
B  0.569289 -0.999289  0.837212 -1.958880
C -0.645749 -1.941364  0.196134  0.536743
D  1.306091 -0.619092 -1.287818  0.231484
E  0.516966  1.699812  0.566997 -0.062426

In [21]:
##Pandas Dataframe
df=pd.DataFrame([[1,2,3,4],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]], index= ['A','B','C','D'], columns= ['W', 'X','Y','Z','D'])

In [22]:
df

W  X  Y  Z    D
A  1  2  3  4  NaN
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [23]:
#Selection single column
df['W']

A    1
B    1
C    1
D    1
Name: W, dtype: int64

In [24]:
#Selection more than one column
df[['W','D']]

W    D
A  1  NaN
B  1  5.0
C  1  5.0
D  1  5.0

In [25]:
#multiplication of two column
df['new']= df['W']*df['D']

In [26]:
df

W  X  Y  Z    D  new
A  1  2  3  4  NaN  NaN
B  1  2  3  4  5.0  5.0
C  1  2  3  4  5.0  5.0
D  1  2  3  4  5.0  5.0

In [28]:
#Deleting the column
df.drop('new',axis=1)

W  X  Y  Z    D
A  1  2  3  4  NaN
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [29]:
df

W  X  Y  Z    D  new
A  1  2  3  4  NaN  NaN
B  1  2  3  4  5.0  5.0
C  1  2  3  4  5.0  5.0
D  1  2  3  4  5.0  5.0

In [30]:
#permannetly delete or place in them 
df.drop('new',axis=1,inplace= True)

In [31]:
df

W  X  Y  Z    D
A  1  2  3  4  NaN
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [33]:
#selction of the rows 
df.loc['A']

W    1.0
X    2.0
Y    3.0
Z    4.0
D    NaN
Name: A, dtype: float64

In [34]:
#checking the condition
df>0

W     X     Y     Z      D
A  True  True  True  True  False
B  True  True  True  True   True
C  True  True  True  True   True
D  True  True  True  True   True

In [35]:
#placing the index 
df.reset_index()

index  W  X  Y  Z    D
0     A  1  2  3  4  NaN
1     B  1  2  3  4  5.0
2     C  1  2  3  4  5.0
3     D  1  2  3  4  5.0

In [43]:
#filling the nan value 
df.fillna(value=1,inplace= True)

In [44]:
df

W  X  Y  Z    D
A  1  2  3  4  1.0
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [45]:
#defines mathematical calucalation
df.describe()

W    X    Y    Z    D
count  4.0  4.0  4.0  4.0  4.0
mean   1.0  2.0  3.0  4.0  4.0
std    0.0  0.0  0.0  0.0  2.0
min    1.0  2.0  3.0  4.0  1.0
25%    1.0  2.0  3.0  4.0  4.0
50%    1.0  2.0  3.0  4.0  5.0
75%    1.0  2.0  3.0  4.0  5.0
max    1.0  2.0  3.0  4.0  5.0

In [121]:
#defines mathematical calculation of columns
df.describe().transpose()

count    mean         std    min     25%    50%     75%    max
col1    4.0    2.50    1.290994    1.0    1.75    2.5    3.25    4.0
col2    4.0  527.25  106.274409  444.0  444.00  499.5  582.75  666.0

In [47]:
df

W  X  Y  Z    D
A  1  2  3  4  1.0
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [48]:
#display 
df.head()

W  X  Y  Z    D
A  1  2  3  4  1.0
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [50]:
#find the index
df.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [53]:
#write data into the csv file 
df.to_csv('try.csv')

In [54]:
#finding the abs 
df.abs()

W    X    Y    Z    D
A  1.0  2.0  3.0  4.0  1.0
B  1.0  2.0  3.0  4.0  5.0
C  1.0  2.0  3.0  4.0  5.0
D  1.0  2.0  3.0  4.0  5.0

In [55]:
#check the bool
df.bool

<bound method NDFrame.bool of    W  X  Y  Z    D
A  1  2  3  4  1.0
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0>

In [57]:
#write in dict
df.to_dict(orient= 'dict')


{'D': {'A': 1.0, 'B': 5.0, 'C': 5.0, 'D': 5.0},
 'W': {'A': 1, 'B': 1, 'C': 1, 'D': 1},
 'X': {'A': 2, 'B': 2, 'C': 2, 'D': 2},
 'Y': {'A': 3, 'B': 3, 'C': 3, 'D': 3},
 'Z': {'A': 4, 'B': 4, 'C': 4, 'D': 4}}

In [58]:
#sorting data 
df.sort(axis=0)

C:\anaconda\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  if __name__ == '__main__':


W  X  Y  Z    D
A  1  2  3  4  1.0
B  1  2  3  4  5.0
C  1  2  3  4  5.0
D  1  2  3  4  5.0

In [59]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [60]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [82]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [96]:
df1.head()

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [98]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

In [100]:
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [101]:
#collecting the unique value in columns
df['col1'].unique()

array([1, 2, 3, 4], dtype=int64)

In [102]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [103]:
#sorting the values by columns
df.sort_values(by='col3')

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [104]:
#finding number of unique value 
df['col1'].nunique()

4

In [105]:
#applying the condition in them 
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [106]:
newdf

col1  col2 col3
3     4   444  xyz

In [116]:
#applying the function in them 
def times(x):
    return x*2
df['col1'].apply(times)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [117]:
#deleting the columns
del df['col3']

In [118]:
df


col1  col2
0     1   444
1     2   555
2     3   666
3     4   444

In [62]:
#concatinations the two dataframe
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [64]:
#concatinations from y -axsis
c=pd.concat([df1,df2],axis=1)

In [65]:
c

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [80]:
#filling the value in all columns
c.fillna(value=13,inplace= True)

In [81]:
c

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  13  13  13  13
1  A1  B1  C1  D1  13  13  13  13
2  A2  B2  C2  D2  13  13  13  13
3  A3  B3  C3  D3  13  13  13  13
4  13  13  13  13  A4  B4  C4  D4
5  13  13  13  13  A5  B5  C5  D5
6  13  13  13  13  A6  B6  C6  D6
7  13  13  13  13  A7  B7  C7  D7

In [86]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [87]:
#applying joi operator in them 
left.join(right, how='right')

A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3

In [94]:
#merging the two dataframe from their keys 
import pandas as pd
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

pd.merge(left, right, on=['key1', 'key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [122]:
#reading the excels 
pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15